export const routes = {
  public: {
    home: '/',
    login: '/auth/login',
    signup: '/auth/signup',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    verifyEmail: '/auth/verify-email',
    courses: '/courses',
    courseDetail: '/courses/:id',
    courseExplore: '/courses/explore',
    courseCheckout: '/courses/:id/checkout',
    pricing: '/pricing',
    about: '/about',
    contact: '/contact',
    help: '/help',
    docs: '/docs',
    careers: '/careers',
    community: '/community',
    status: '/status',
    blog: '/blog',
    search: '/search',
  },
  protected: {
    dashboard: '/dashboard',
    studentDashboard: '/student/dashboard',
    instructorDashboard: '/instructor/dashboard',
    adminDashboard: '/admin/dashboard',
    myCourses: '/my-courses',
    coursePlayer: '/learn/:courseId',
    courseDiscussions: '/courses/:courseId/discussions',
    quizTaker: '/courses/:courseId/quiz/:quizId',
    quizBuilder: '/courses/:courseId/quiz-builder',
    quizResults: '/quiz-results',
    certificates: '/certificates',
    messages: '/messages',
    activity: '/activity',
    profile: '/profile',
    notifications: '/notifications',
    orders: '/orders',
    orderSuccess: '/order-success',
  },
  admin: {
    adminDashboard: '/admin/dashboard',
    courseManager: '/admin/courses',
    userManagement: '/admin/users',
    analytics: '/admin/analytics',
    approvals: '/admin/approvals',
    systemSettings: '/admin/settings',
  },
  cms: {
    content: '/cms/content',
    uploadLesson: '/cms/upload/:courseId',
    mediaLibrary: '/cms/media',
    pageBuilder: '/cms/pages',
    blogEditor: '/cms/blog',
  },
} as const;

export type Routes = typeof routes;